language: node_js
node_js:
- "0.12"
sudo: false
cache:
  directories:
  - bower_components
  - node_modules
before_install:
- bundle install
- rm -fr bower_components
- bower install -F
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c8c40bc13ee38867f698
    on_success: change
    on_failure: always
    on_start: never
